package java0507_exception;

import java.util.Scanner;

public class Java152_exception {

	public static void main(String[] args) {
		int[] data = new int[2];
		for(int i=0; i<data.length; i++) {
			data[i] = inputData();
			
		}
		System.out.printf("두 수의 합은 : %d\n", data[0], data[1]);
	} //end main()

	public static int inputData(int index) {
		Scanner sc = new Scanner(System.in);
		int num;
		while(true) {
			System.out.printf("%d번째 정수를 입력하세요.\n", index+1);
			num = sc.nextInt(); //여기서 num에 값이 할당됨.
			return num;
		}
		
	} //end inputData()
	
} //end class
